# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_guest"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bitfield-struct.workspace = true
hvdef.workspace = true
log.workspace = true
open_enum.workspace = true
opentmk_core.workspace = true
spin.workspace = true
thiserror.workspace = true
zerocopy.workspace = true

[target.'cfg(target_os = "uefi")'.dependencies]

[lints]
workspace = true
