# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "opentmk_executor"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cfg-if.workspace = true
hvdef.workspace = true
log.workspace = true
opentmk_core.workspace = true
spin.workspace = true
zerocopy.workspace = true
postcard = { workspace = true, features = ["alloc"] }
opentmk_exec_packet.workspace = true
opentmk_decoder.workspace = true
uefi = { workspace = true, features = ["alloc"] }
vmbus_guest.workspace = true

[lints]
workspace = true
